micronaut:
  application:
    name: r2dbc-library-compatibility
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5432/postgres
      username: sa
      password: ''
netty:
  default:
    allocator:
      max-order: 3
